language: python

python:
  - "3.7"

cache: pip

sudo: required
dist: bionic

services:
  - docker

before_install:
  - ./ci/bootstrap_database.sh
  - docker exec -i faf-db mysql -uroot -pbanana faf-league -e "show tables;"
  - ./ci/init-rabbitmq.sh
  - python -m pip install pipenv

install:
  - pipenv sync --dev
  - docker build --build-arg TRAVIS_TAG -t faf-league-service .
  - pipenv run migrate-develop
  - docker exec -i faf-db mysql -uroot -pbanana faf-league -e "select * from league;"


script:
  - scripts/run_tests_with_coverage.sh
  - sed -i.bak s#/code/#$(pwd)/#g .coverage

after_success:
  - coveralls
